salesforce/eslint-plugin-lwc

- README.md
- docs/rules/no-dupe-class-members.md
- lib/index.js
- lib/rules/no-dupe-class-members.js
- test/lib/rules/no-dupe-class-members.js
This rule prevents usage of duplicate class members (fields and methods) on the same class. Here is an example of code the rule would flag that `bar` is declared twice on the same class.
```js
class Foo {
bar;
bar() {}
}
```
> Add no-dupe-class-member rule

- package.json
Contains new rule to disallow @api properties to start with the camel case letter.
> chore: upgrade to 0.8.0

- package.json
- test/lib/rules/no-rest-parameter.js
- test/lib/shared.js
- yarn.lock
Upgrading ESLint which required paths for resolvers as seen here: https://github.com/eslint/eslint/blob/master/docs/user-guide/migrating-to-6.0.0.md#rule-tester-parser
> chore: upgrade ESLint

- test/lib/rules/no-rest-parameter.js
This PR makes all the `RuleTester` constructor uniform, sharing the same config.
> test: make rule tester uniform

- .circleci/config.yml
- package.json
- test/mocha.opts
- yarn.lock
* **⚠️Drop support for Node 8 ⚠️**. The next release of this package needs to be a major release.
* Upgrade all the project `devDependencies`.
* Fix misc. deprecations for `mocha` and `lint-staged`
> chore: Upgrade dev dependencies

- README.md
- docs/rules/no-api-reassignments.md
- lib/index.js
- lib/rules/no-api-reassignments.js
- lib/rules/no-leading-uppercase-api-name.js
- lib/util/decorator-util.js
- test/lib/rules/no-api-reassignments.js
Add `no-api-reassignments` linting rule to prevent public property reassignment.
This PR also unifies public properties and methods gathering.
Fixes #27.
W-7200635
> feat: Add no-api-reassignments rule

- README.md
- docs/rules/no-leaky-event-listeners.md
- lib/index.js
- lib/rules/no-leaky-event-listeners.js
- test/lib/rules/no-leaky-event-listeners.js
This PR introduces the `lwc/no-leaky-event-listeners` linting rule. This rule prevents common patterns from event listeners leaking memory.
W-7109631
> feat: Add no-leaky-event-listeners rule

- docs/rules/no-unknown-wire-adapters.md
- lib/rules/no-unknown-wire-adapters.js
- package.json
- test/lib/rules/no-unknown-wire-adapters.js
In some cases like [apex adapters](https://developer.salesforce.com/docs/component-library/documentation/en/lwc/lwc.apex), we don’t know the adapters before hand.
This PR adds support for globs in the `module` and `identifier` property, allowing (mark as known) all wire adapters matching the `module` and `identifier` glob patterns.
> feat(no-unknown-wire-adapters): support module and identifier as a glob pattern

- docs/rules/no-leaky-event-listeners.md
The previous example was an invalid JavaScript code. This PR fixes the example and adds more detail on why the event listener removal doesn't work as expected.
> Fix no-leaky-event-listeners example

- .circleci/config.yml
- package.json
- yarn.lock
Until now eslint-plugin-lwc defined a loose peer dependency against eslint `>=6`. With this PR, this dependency is restricted to eslint `^6` and eslint `^7`. To ensure that the plugin works as expected against the different supported versions of eslint, the CI now runs a build matrix.
Restricting the eslint peer dependency from `>=6` to `^6 || ^7` is not a breaking change since the latest published version of eslint is `7.6.0`.
> chore: Add build for eslint@7

- README.md
- docs/rules/prefer-custom-event.md
- lib/index.js
- lib/rules/prefer-custom-event.js
- test/lib/rules/prefer-custom-event.js
This PR adds a new linting rule to suggest using `CustomEvent` instead of `Event`.
**⚠️ This PR need to be merged after #47 ⚠️**
> feat: Add prefer-custom-event rule

- docs/rules/valid-api.md
- lib/rules/valid-api.js
- test/lib/rules/valid-api.js
This PR update the `valid-api` documentation with the newly introduced option and correct the option name (`disallowUnderscoreUppercaseMix`).
> docs: update valide-api README and correct option name

- README.md
- docs/rules/no-attributes-during-construction.md
- lib/index.js
- lib/rules/no-attributes-during-construction.js
- lib/util/component.js
- test/lib/rules/consistent-component-name.js
- test/lib/rules/no-attributes-during-construction.js
> feat: no-attributes-during-construction

- lib/rules/no-attributes-during-construction.js
- test/lib/rules/no-attributes-during-construction.js
`AssignmentExpression` > `MemberExpression` > `ThisExpression`
We were doing checks for `AssignmentExpression` and `ThisExpression` but not `MemberExpression`.
> fix: handle case where assignment expression isn't member expression

- README.md
- package.json
- test/lib/shared.js
- yarn.lock
The `babel-eslint` NPM package has been deprecated. It has been replaced by `@babel/eslint-parser` as moved to the Babel monorepo. This PR updates the peer dependency from `babel-eslint` to `@babel/eslint-parser`. 
⚠️ This is a breaking change. Since this package is been stable for a year now, I think it would be a good occasion to release this change under `1.0.0`. 
Fixes #64
> Replace babel-eslint with @babel/eslint-parser

- lib/rules/no-unknown-wire-adapters.js
- test/lib/rules/no-unknown-wire-adapters.js
This PR updates the [`lwc/no-unknown-wire-adapters`](https://github.com/salesforce/eslint-plugin-lwc/blob/master/docs/rules/no-unknown-wire-adapters.md) so that the error message is reported in the `@wire` usage node instead of the import (declaration).
> fix: enhance no-unknown-wire-adapters by reporting in wire usage

- .circleci/config.yml
- package.json
When installing this package with eslint@6, the following message gets printed. ([example](https://app.circleci.com/pipelines/github/salesforce/eslint-plugin-lwc/194/workflows/c8b537f0-f57a-47fe-b471-72b1331c5536/jobs/255/parallel-runs/0/steps/0-105))
```
warning " > @babel/eslint-parser@7.13.14" has incorrect peer dependency "eslint@>=7.5.0".
```
This is because @babel/eslint-parser@7 is incompatible with eslint@6. Dropping support for a peerDependency version should be considered as a breaking change. However, since eslint@6 support is already broken today, we should release this as a simple fix.
> fix: Drop ESLint 6 support

- README.md
- docs/rules/no-template-children.md
- lib/index.js
- lib/rules/no-template-children.js
- test/lib/rules/no-template-children.js
Adds a rule to check for patterns like `this.template.firstChild`, which is commonly used today in shadow-DOM-using code to check whether the component has rendered yet (e.g. `if (!this.template.firstChild) { /* ... */ }`), or to retrieve the first element defined in the template HTML.
This will not work in native shadow DOM in certain browsers, as described in the added docs. `this.template.querySelector` is encouraged as an alternative.
W-9742708
> feat: Add no-template-children rule

- .circleci/config.yml
- lib/rules/no-attributes-during-construction.js
- lib/rules/no-deprecated.js
- lib/rules/no-dupe-class-members.js
- lib/rules/valid-api.js
- lib/rules/valid-track.js
- lib/rules/valid-wire.js
- lib/util/isClassField.js
- package.json
- test/integration.js
- test/lib/rules/no-attributes-during-construction.js
- test/lib/rules/no-dupe-class-members.js
- yarn.lock
Updates dependencies and adds supports for ESLint 8. ESLint 7 is still supported.
> fix: support eslint 8 and 7

- README.md
- docs/rules/no-dupe-class-members.md
- lib/rules/no-dupe-class-members.js
- test/lib/rules/no-dupe-class-members.js
> chore: Deprecate `no-dupe-class-member` rule

- package.json
- yarn.lock
This resolves the issue described here:
https://www.huntr.dev/bounties/e4e1393c-d590-4492-9f43-8be3f3321629/
> chore: upgrade minimatch to resolve security issue

- README.md
- docs/rules/no-disallowed-lwc-imports.md
- lib/index.js
- lib/rules/no-disallowed-lwc-imports.js
- test/lib/rules/no-disallowed-lwc-imports.js
Fixes: https://github.com/salesforce/lwc/issues/1284 and W-10151021
Adds a rule to disallow restricted APIs from the `lwc` package.
> feat: add no-disallowed-lwc-imports rule

- lib/rules/no-disallowed-lwc-imports.js
- test/lib/rules/no-disallowed-lwc-imports.js
When trying to release into `eslint-config-lwc`, I noticed a bug in the `no-disallowed-lwc-imports` rule. It fails on code like this:
```js
export function foo() {}
```
```js
export const foo = 'foo'
```
This throws `TypeError: Cannot read properties of null (reading 'type')` at this line:
https://github.com/salesforce/eslint-plugin-lwc/blob/6128fbe36a262b12a8e66d9d3d2a2a902ea4afde/lib/rules/no-disallowed-lwc-imports.js#L37
The problem is that we weren't distinguishing these usages from exports like `export { foo } from 'lwc'`.
This PR fixes that.
> fix: fix named variable/function exports

- .circleci/config.yml
- package.json
One step closer to a 1-button release process.
The remaining work involves git automation around branch protection, pushing the actual changes to the remote, and changelog generation.
> chore: add release scripts

- docs/rules/no-disallowed-lwc-imports.md
- lib/rules/no-disallowed-lwc-imports.js
- test/lib/rules/no-disallowed-lwc-imports.js
This PR introduces the new `allowList` option to the `no-disallowed-lwc-imports` rule. When set this option overrides the default list of available APIs on `lwc`. 
**Misc:**
- Updated the error message to be more generic.
> Add allowList option to `no-disallowed-lwc-imports`

- docs/rules/no-disallowed-lwc-imports.md
- lib/rules/no-disallowed-lwc-imports.js
- test/lib/rules/no-disallowed-lwc-imports.js
Adds two new options to allow bare imports and exports for backwards compatibility purposes.
See: W-11690641
> feat: add options to disable export/bare import validation

- lib/rules/consistent-component-name.js
- test/lib/rules/consistent-component-name.js
The `lwc/consistent-component-name` rule fails for `.ts` files as described in #109 . This PR aims to solve it by agnostically removing the extension from the file being checked, thus including `.js` and `.ts` files. This also opens up to other file extensions, but from what I gather, that shouldn't cause problems.
> Add `lwc/consistent-component-name` support for `.ts` files

- docs/rules/no-restricted-browser-globals-during-ssr.md
- lib/util/ssr.js
- test/lib/rules/no-restricted-browser-globals-during-ssr.js
Allows
```
renderedCallback() {
if(!import.meta.env.SSR) {
// browser specific code allowed here.
}
}
```
> fix: allow `import.meta.env.SSR` check

- README.md
- docs/rules/no-node-env-in-ssr.md
- lib/index.js
- lib/rule-helpers.js
- lib/rules/no-node-env-in-ssr.js
- test/lib/rules/no-node-env-ssr.js
- test/lib/rules/no-restricted-browser-globals-during-ssr.js
Disallow `process.env.NODE_ENV` during SSR, see https://salesforce.quip.com/6J0RAYat9M9v#temp:C:MMbc006360e39d2469babb79cede
> feat: add no node env ssr rule

- .circleci/config.yml
As of 2023-09-11, v16 is EOL and v18 is LTS
> chore: node v18

- lib/rule-helpers.js
- test/lib/rules/no-restricted-browser-globals-during-ssr.js
The `no-browser-globals-during-ssr` is very limited in its current detection capabilities as it doesn't detect the use of non-SSRable browser APIs outside the context of LWCs. If bundles e.g. reference browser-only APIs in utility methods, these references pass without warnings. This PR keeps the old behavior for LWCs, but warns/errors about the use of non-SSRable Web APIs more aggressively outside LWCs.
> feat: update rule `no-browser-globals-during-ssr` to be more open

- .circleci/config.yml
Use node v18 while deploying in Circle CI.
> fix: use node v18 while deploying

- README.md
- lib/rules/no-restricted-browser-globals-during-ssr.js
- package.json
- test/lib/rules/consistent-component-name.js
- test/lib/rules/no-api-reassignments.js
- test/lib/rules/no-async-await.js
- test/lib/rules/no-async-operation.js
- test/lib/rules/no-attributes-during-construction.js
- test/lib/rules/no-deprecated.js
- test/lib/rules/no-disallowed-lwc-imports.js
- test/lib/rules/no-document-query.js
- test/lib/rules/no-dupe-class-members.js
- test/lib/rules/no-for-of.js
- test/lib/rules/no-inner-html.js
- test/lib/rules/no-leading-uppercase-api-name.js
- test/lib/rules/no-leaky-event-listeners.js
- test/lib/rules/no-node-env-ssr.js
- test/lib/rules/no-rest-parameter.js
- test/lib/rules/no-restricted-browser-globals-during-ssr.js
- test/lib/rules/no-template-children.js
- test/lib/rules/no-unexpected-wire-adapter-usages.js
- test/lib/rules/no-unknown-wire-adapters.js
- test/lib/rules/no-unsupported-ssr-properties.js
- test/lib/rules/prefer-custom-event.js
- test/lib/rules/valid-api.js
- test/lib/rules/valid-graphql-wire-adapter-callback-parameters.js
- test/lib/rules/valid-track.js
- test/lib/rules/valid-wire.js
- test/lib/shared.js
- yarn.lock
We use `@babel/eslint-parser` as our parser, so for basic typescript support we just need to drop in `@babel/preset-typescript`. I also copied most of the tests and sprinkled in TypeScript syntax, although it's not always relevant to the rule being tested (and it's definitely not exhaustive).
> test: add typescript tests

- docs/rules/valid-api.md
- lib/rules/valid-api.js
- test/lib/rules/valid-api.js
This PR updates the restriction on `data` to not include `data` itself since this is a valid api name. It also adds `dataset` to the list of reserved apis.
> Update @lwc/lwc/valid-api eslint for data

- package.json
BREAKING CHANGE: The ssr related rules will be renamed from `@lwc/lwc/ssr/no-xxx` to `@lwc/lwc/ssr-no-xxx`
Follow up to this comment https://github.com/salesforce/eslint-plugin-lwc/pull/180#pullrequestreview-2529706658
> feat!: major release v2.0.0

- .circleci/config.yml
- README.md
- lib/index.js
redoing https://github.com/salesforce/eslint-plugin-lwc/pull/181 as I lost it to a force update.
> fix: add meta tags for plugin exports
